# Generated by Django 3.1.1 on 2020-10-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sungem', '0002_auto_20201002_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='module',
            field=models.CharField(max_length=20),
        ),
    ]
